import oracledb
from faker import Faker

# Connect
connection = oracledb.connect(
    user="airflow",
    password="airflow",
    dsn="localhost:1522/XEPDB1"
)
 
cursor = connection.cursor()

# Step 1: Create table
cursor.execute("""
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE people';
    EXCEPTION
        WHEN OTHERS THEN
               IF SQLCODE != -942 THEN
                    RAISE;
                END IF;
    END;         
""")

cursor.execute("""
     CREATE TABLE people (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR2(100),
            email VARCHAR2(100)
        )
""")

# Step 2: Insert fake data
fake = Faker()
for _ in range(10):
    name = fake.name()
    email = fake.email()
    cursor.execute("INSERT INTO people (name, email) VALUES (:1, :2)", (name, email))

connection.commit()
cursor.close()
connection.close()

print("table created abd 10 rows inserted.")